# Package definition for watchexec

package_name: watchexec
github_repo: watchexec/watchexec
artifact_format: tar.xz
description: "Execute commands in response to file modifications"

# Build for all Debian suites and all supported architectures.
